- package.json
- src/app/app.component.html
- src/app/app.component.scss
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/mapmyproperty/esrimap/esrimap.component.html
- src/app/mapmyproperty/esrimap/esrimap.component.ts
- src/app/mapmyproperty/homepage/homepage.component.html
- src/app/shared/store/GraphicsStore.component.html
- src/app/shared/store/GraphicsStore.component.ts
- src/app/shared/store/graphics.actions.ts
- src/app/shared/store/graphics.reducer.ts
Fixes #7 to a certain extent. 
Needs extensive testing.
> added keyboard and undo redo support

- src/app/mapmyproperty/esrimap/esrimap.component.ts
- src/app/mapmyproperty/homepage/homepage.module.ts
- src/app/mapmyproperty/sidebar/sidebar.component.html
- src/app/mapmyproperty/sidebar/sidebar.component.scss
- src/app/mapmyproperty/sidebar/sidebar.component.ts
- src/app/shared/components/color-picker/color-picker.component.html
- src/app/shared/components/color-picker/color-picker.component.scss
- src/app/shared/components/color-picker/color-picker.component.ts
- src/app/shared/components/color-picker/color-picker.popover.component.html
- src/app/shared/components/color-picker/color-picker.popover.component.ts
- src/app/shared/store/graphics.reducer.ts
- src/app/shared/styles/CustomSlider.scss
- src/app/shared/styles/sidebar.scss
- src/app/shared/utils/GraphicStyles.ts
Fixes #14 to a certain extent.
> Added a horizontal width slider

- src/app/shared/components/drawtools/DrawTools.interface.ts
- src/app/shared/components/drawtools/drawtools.component.html
- src/app/shared/components/drawtools/drawtools.component.ts
- src/app/shared/utils/GraphicStyles.ts
Work in the direction for fixing #48
> adding polygon fill

- src/app/mapmyproperty/esrimap/esrimap.component.ts
- src/app/shared/components/drawtools/drawtools.component.ts
- src/app/shared/components/drawtools/store.selector.ts
- src/app/shared/store/GraphicsStore.component.ts
- src/app/shared/store/graphics.reducer.ts
- src/app/shared/store/graphics.state.ts
- src/app/shared/utils/DrawUtils.ts
improved sketchview model update event to check for graphics equality
> improved sketchview model update event to check for graphics equality

- src/app/mapmyproperty/esrimap/esrimap.component.ts
- src/app/shared/components/color-picker/color-picker.component.ts
- src/app/shared/components/drawtools/drawtools.component.html
- src/app/shared/components/drawtools/drawtools.component.ts
- src/app/shared/utils/DrawUtils.ts
- src/app/shared/utils/GraphicStyles.ts
- src/app/shared/utils/SketchViewModelUitls.ts
> Fixed #52 - Memory Leak on Color Picker

- monitor1.code-workspace
- src/app/mapmyproperty/esrimap/esrimap.component.html
- src/app/mapmyproperty/esrimap/esrimap.component.scss
- src/app/mapmyproperty/esrimap/esrimap.component.ts
- src/app/shared/components/drawtools/TextUtils.ts
- src/app/shared/components/drawtools/drag.ts
- src/app/shared/components/drawtools/drawtools.component.html
- src/app/shared/components/drawtools/drawtools.component.scss
- src/app/shared/components/drawtools/drawtools.component.ts
- src/app/shared/store/GraphicsStore.component.html
- src/app/shared/store/GraphicsStore.component.scss
- src/app/shared/store/GraphicsStore.component.ts
- src/app/shared/store/GraphicsStore.module.ts
- src/app/shared/utils/CreateGraphicsLayer.ts
- tsconfig.code-workspace
Adding text input support.
Still far way from #62
> Draw tools with partial text input support

- src/app/shared/components/drawtools/TextUtils.ts
- src/app/shared/components/drawtools/drawtools.component.scss
- src/app/shared/components/drawtools/drawtools.component.ts
- src/styles.scss
https://github.com/bishrant/MapMyProperty/blob/443eaa17c8ed87bf753e16800c9afb5f584a4ff5/src/app/shared/components/drawtools/TextUtils.ts#L36-L95
> partial fix of #64 towards removal of angular renderer

- package-lock.json
- package.json
- src/app/planmylandoperation/esrimap/esrimap.component.html
- src/app/planmylandoperation/esrimap/esrimap.module.ts
- src/app/planmylandoperation/esrimap/sens-areas/sens-areas.component.html
- src/app/planmylandoperation/esrimap/sens-areas/sens-areas.component.scss
- src/app/planmylandoperation/esrimap/sens-areas/sens-areas.component.ts
- src/app/planmylandoperation/pmloUtils/layers.ts
- src/app/planmylandoperation/utils/pmloUtils.ts
- src/app/shared/utils/GeometryEngine.ts
- src/styles.scss
First part of Sensitive Areas tool
> Sensitive Areas

- src/app/shared/components/drawtools/drawtools.component.html
- src/app/shared/components/drawtools/drawtools.component.ts
- src/app/shared/components/drawtools/drawtools.module.ts
- src/app/shared/components/pointcontrol/pointcontrol.component.html
- src/app/shared/components/pointcontrol/pointcontrol.component.scss
- src/app/shared/components/pointcontrol/pointcontrol.component.ts
- src/app/shared/components/pointcontrol/pointcontrol.module.ts
- src/app/shared/utils/DrawUtils.ts
Point tool is separated into its own module so that the DrawTools component doesnot become too long and hard to manage.
> Started working on Point tools

- package-lock.json
- src/app/shared/components/drawtools/DrawTools.interface.ts
- src/app/shared/components/drawtools/drawtools.component.html
- src/app/shared/components/drawtools/drawtools.component.ts
- src/app/shared/components/drawtools/drawtools.module.ts
- src/app/shared/components/drawtools/fillstyle/fillstyle.component.html
- src/app/shared/components/drawtools/fillstyle/fillstyle.component.scss
- src/app/shared/components/drawtools/fillstyle/fillstyle.component.ts
- src/app/shared/components/drawtools/fillstyle/fillstyle.module.ts
- src/app/shared/components/drawtools/linestyle/linestyle.component.html
- src/app/shared/components/drawtools/linestyle/linestyle.component.scss
- src/app/shared/components/drawtools/linestyle/linestyle.component.ts
- src/app/shared/components/drawtools/linestyle/linestyle.module.ts
- src/app/shared/components/pointcontrol/pointcontrol.component.html
- src/app/shared/components/pointcontrol/pointcontrol.component.scss
- src/app/shared/components/pointcontrol/pointcontrol.component.ts
- src/app/shared/utils/DrawUtils.ts
- src/app/shared/utils/GeometryEngine.ts
> Almost completed draw tools

- src/app/shared/components/drawtools/TextUtils.ts
- src/app/shared/components/drawtools/drawtools.component.ts
- src/app/shared/components/import-export/ImportExport.component.html
- src/app/shared/components/import-export/ImportExport.component.ts
- src/app/shared/components/import-export/ImportExport.module.ts
- src/app/shared/components/import-export/KMLUtils.ts
- src/app/shared/store/graphics.reducer.ts
- src/app/shared/utils/SketchViewModelUitls.ts
Needs further work on SHP, KML, GPX.
Also needs this to be tested. No critical tests has been performed yet.
> Added export to and import from MMP

- .prettierrc.json
- src/app/shared/components/import-export/DefaultSymbols.ts
- src/app/shared/components/import-export/FeatureCollectionUtils.ts
- src/app/shared/components/import-export/SHPUtils.ts
> Added more extensive shapefile parsing Fixes #99

- package-lock.json
- src/app/app.module.ts
- src/app/shared/components/loader/loader.component.html
- src/app/shared/components/loader/loader.component.scss
- src/app/shared/components/loader/loader.component.ts
- src/app/shared/components/loader/loader.module.ts
- src/app/shared/components/print-tool/map-dialog.componenet.ts
- src/app/shared/components/print-tool/print-tool.component.ts
- src/app/shared/components/print-tool/print-tool.module.ts
- src/app/shared/services/error/GlobalErrorHandler.ts
- src/app/shared/services/error/error.service.ts
- src/app/shared/services/error/logging.service.ts
- src/app/shared/services/error/notification.service.ts
Added a working version of global error handler and logging using DotNet core API as backend.
> Global error logging

- src/app/app.component.ts
- src/app/shared/components/print-tool/map-dialog.componenet.ts
- src/app/shared/components/print-tool/print-tool.component.html
- src/app/shared/components/print-tool/print-tool.component.ts
- src/app/shared/components/print-tool/print-tool.module.ts
- src/app/shared/services/error/GPServiceError.ts
- src/app/shared/services/error/GlobalErrorHandler.ts
- src/app/shared/services/error/logging.service.ts
- src/assets/appconfig.js
- src/assets/config.json
- src/config.ts
- src/main.ts
App settings are stored inside assets/config.json instead of some js/ts files.
Settings could be swapped as long as the entry exists in config.ts file.
Fixes #108 
Also polishes log reporting API to fix #107
> Adding runtime configuration functionality

- src/app/mapmyproperty/esrimap/esrimap.component.ts
> Fixes Minimize the use of Angular renderer #64

- package-lock.json
- package.json
- src/app/mapmyproperty/esrimap/esrimap.component.html
- src/app/mapmyproperty/mmphome.module.ts
- src/app/shared/components/drawtools/drawtools.module.ts
- src/app/shared/components/header/header.component.html
- src/app/shared/components/header/header.component.scss
- src/app/shared/components/header/header.component.ts
- src/app/shared/components/header/header.module.ts
- src/tailwind.scss
- stylelint.config.js
Converted FlexLayout and Material design based header module to tailwind css
> Converted FlexLayout and Material design based header module to tailwind css

- src/app/app.module.ts
- src/app/drawmyranch/dmrhome.module.ts
- src/app/planmylandoperation/esrimap/esrimap.component.html
- src/app/planmylandoperation/planmylandoperation.module.ts
- src/app/shared/components/color-picker/color-picker.component.scss
- src/app/shared/components/color-picker/color-picker.popover.component.html
- src/app/shared/components/drawtools/drawtools.component.html
- src/app/shared/components/drawtools/drawtools.module.ts
- src/app/shared/components/textcontrols/textcontrols.module.ts
- src/app/shared/store/GraphicsStore.module.ts
> Removed FxLayoutModule dependency

- package-lock.json
- package.json
- src/app/mapmyproperty/mmphome.component.scss
- src/app/planmylandoperation/sidebar/elevation-profile/elevation-profile.component.html
- src/app/planmylandoperation/sidebar/elevation-profile/elevation-profile.module.ts
- src/app/shared/components/print-tool/print-tool.component.html
- src/app/shared/components/print-tool/print-tool.module.ts
- src/tailwind.scss
- tailwind.config.js
Still exists in couple of components:
`sens-areas.component.html' 
'soils.component.html`
> Partially removed MatCheckboxModule

- src/app/drawmyranch/dmrhome.module.ts
- src/app/mapmyproperty/esrimap/esrimap.component.html
- src/app/mapmyproperty/esrimap/esrimap.module.ts
- src/app/mapmyproperty/mmphome.component.scss
- src/app/planmylandoperation/esrimap/esrimap.component.html
- src/app/planmylandoperation/esrimap/esrimap.module.ts
- src/app/planmylandoperation/sidebar/elevation-profile/elevation-profile.component.html
- src/app/planmylandoperation/sidebar/elevation-profile/elevation-profile.module.ts
- src/app/planmylandoperation/sidebar/sens-areas/sens-areas.component.html
- src/app/planmylandoperation/sidebar/sens-areas/sens-areas.component.ts
- src/app/planmylandoperation/sidebar/soils/soils.component.html
- src/app/shared/components/accordion-panel/accordion-component.scss
- src/app/shared/components/accordion-panel/accordion-panel.component.ts
- src/app/shared/components/accordion-panel/accordion.component.ts
- src/app/shared/components/accordion-panel/accordion.panel.module.ts
- src/app/shared/components/drawtools/drawtools.component.html
- src/app/shared/components/drawtools/drawtools.module.ts
- src/app/shared/components/drawtools/fillstyle/fillstyle.module.ts
- src/app/shared/components/drawtools/linestyle/linestyle.module.ts
- src/app/shared/components/import-export/ImportExport.component.html
- src/app/shared/components/import-export/ImportExport.module.ts
- src/app/shared/components/print-tool/print-tool.component.html
- src/app/shared/components/print-tool/print-tool.module.ts
- src/app/shared/components/textcontrols/textcontrols.module.ts
- src/app/shared/store/GraphicsStore.module.ts
- src/app/shared/styles/themes/mmp.theme.scss
- src/styles.scss
> Removed MatExpansion panel and its module

- src/app/mapmyproperty/esrimap/esrimap.component.html
- src/app/mapmyproperty/esrimap/esrimap.component.ts
- src/app/planmylandoperation/esrimap/esrimap.component.html
- src/app/shared/components/drawtools/drawtools.component.html
- src/app/shared/components/drawtools/drawtools.component.ts
- src/app/shared/store/GraphicsStore.component.ts
- src/app/shared/styles/BodyFrame.scss
Delete button and Edit button not showing up on graphics selection. z-index of undo higher than zoom buttons
Does not completely fix #146
> Delete button and Edit button not showing up on graphics selection.

- src/app/mapmyproperty/esrimap/esrimap.component.ts
- src/app/planmylandoperation/esrimap/esrimap.component.ts
Fixes portion of #196 
- delete key not working for geometries ✔️
> Fixes delete keyboard issue

- src/app/shared/components/color-picker/color-picker.popover.component.ts
- src/app/shared/components/drawtools/drawtools.component.ts
- src/app/shared/services/TextControlSelection-service.ts
Also text delete button was not showing up.
Fixes first issue that Shruthi had.
> Fixed issue with labels not updating.

- src/app/planmylandoperation/esrimap/esrimap.component.html
- src/app/shared/components/import-export/ImportExport.component.ts
- src/app/shared/components/import-export/OldMMPUtils.ts
- src/app/shared/components/print-tool/print-tool.component.ts
- src/app/shared/utils/DrawUtils.ts
- src/app/shared/utils/SHPUtils.ts
> Draw tools bugs

- src/app/mapmyproperty/esrimap/esrimap.component.html
- src/app/mapmyproperty/esrimap/esrimap.component.ts
- src/app/planmylandoperation/esrimap/esrimap.component.ts
- src/app/planmylandoperation/esrimap/esrimap.service.ts
- src/app/shared/components/accordion-panel/accordion-panel.component.ts
- src/app/shared/components/drawtools/drawtools.component.ts
Draw panels also opens once a graphic is selected
> Draw panels will now open by default

- src/app/mapmyproperty/sidebar/themes/themes.component.ts
- src/app/planmylandoperation/esrimap/esrimap.service.ts
- src/app/planmylandoperation/pmloUtils/notifications.service.ts
- src/app/planmylandoperation/sidebar/soils/soils-table/table-header.ts
- src/app/shared/components/accordion-panel/accordion-panel.component.ts
- src/app/shared/components/accordion-panel/accordion-panel.service.ts
- src/app/shared/components/accordion-panel/accordion.component.ts
- src/app/shared/components/drawtools/TextUtils.ts
- src/app/shared/components/header/header.component.ts
- src/app/shared/components/help-button/help-button.component.ts
- src/app/shared/components/import-export/ImportExport.component.ts
- src/app/shared/components/loader/loader.component.ts
- src/app/shared/components/textcontrols/textcontrols.component.ts
- src/app/shared/layers/NAIPLayers.ts
- src/app/shared/lib/angular-modal/draggable/draggable.directive.ts
- src/app/shared/lib/angular-modal/modal/modal.component.ts
- src/app/shared/services/Loader.service.ts
- src/app/shared/services/PrintTask.service.ts
- src/app/shared/services/TextControlSelection-service.ts
- src/app/shared/services/culvert-size.service.ts
- src/app/shared/services/error/GlobalErrorHandler.ts
- src/app/shared/services/error/error.service.ts
- src/app/shared/services/mapview.service.ts
- src/app/shared/utils/SHPUtils.ts
- src/app/shared/utils/WebMapAsJsonUtils.ts
- src/main.ts
Fixes #232.
Fixes linter issues. Now ~200 left
> Enhance elevation profile

- src/app/shared/components/drawtools/GeometryEngineUtils.ts
- src/app/shared/components/drawtools/drawtools.component.ts
> Fixed Drawing tool not syncing if changed during update #252

- src/app/shared/components/print-tool/print-tool.component.html
- src/app/shared/components/print-tool/print-tool.component.scss
- src/app/shared/components/print-tool/print-tool.component.ts
> Print tool

- src/app/shared/services/culvert-size.service.ts
- src/app/shared/services/elevation-profile/Uitls.ts
- src/app/shared/services/elevation-profile/elevation-profile.service.ts
- src/assets/config.json
- src/config.ts
Fixed a bug in elevation profile graph.
> Updating backend api endpoints.

- src/app/planmylandoperation/esrimap/esrimap.component.html
- src/app/planmylandoperation/esrimap/esrimap.component.ts
- src/app/planmylandoperation/sidebar/culvert-size/culvert-size.component.ts
- src/app/planmylandoperation/sidebar/elevation-profile/elevation-profile.component.ts
- src/app/shared/components/drawtools/drawtools.component.ts
- src/app/shared/components/measurement-widget/measurement-widget.component.ts
- src/app/shared/services/SketchSelectionService.ts
- src/app/shared/services/culvert-size.service.ts
- src/app/shared/utils/SketchViewModelUitls.ts
> New draw tools

- src/app/shared/components/color-picker/color-picker.component.ts
- src/app/shared/components/color-picker/color-picker.popover.component.ts
- src/app/shared/components/import-export/ImportExport.component.ts
- src/app/shared/components/measurement-widget/measurement-widget.component.scss
- src/app/shared/components/overlay-layers-widget/overlay-layers-widget.component.html
- src/app/shared/components/overlay-layers-widget/overlay-layers-widget.component.scss
- src/app/shared/services/ColorsPopover.service.ts
> Styling updates and dynamic color picker updates

- src/app/shared/components/site-policies/site-policies.component.html
- src/app/shared/components/site-policies/site-policies.component.ts
- src/app/shared/layers/NAIPLayers.ts
Also fixed copyright year in footer
Fixes #304
> Updated TNRIS image services

- src/app/mapmyproperty/sidebar/themes/themes.component.html
- src/app/mapmyproperty/sidebar/themes/themes.component.ts
- src/app/mapmyproperty/sidebar/themes/themes.module.ts
- src/app/planmylandoperation/esrimap/esrimap.component.ts
- src/app/planmylandoperation/esrimap/esrimap.service.ts
- src/app/shared/components/overlay-layers-widget/overlay-layers-widget.component.html
- src/app/shared/components/overlay-layers-widget/overlay-layers-widget.component.ts
- src/app/shared/utils/CreateDynamicLayers.ts
- src/app/shared/utils/LayerUtils.ts
- src/assets/config.json
- src/config.ts
Fixes #316 that allows us to lazily load overlay layers to minimize those network requests that are not needed on first application load.
> Map My Property Themes

- src/app/planmylandoperation/esrimap/esrimap.component.ts
- src/app/planmylandoperation/esrimap/esrimap.service.ts
> Error: Cannot read property `panelTitle` of null

- src/app/shared/utils/FeatureCollectionUtils.ts
> Import tool add handler for parsing multi-polygon shapefiles

- src/app/planmylandoperation/sidebar/soils/soils.component.ts
- src/app/shared/components/print-tool/print-tool.component.ts
- src/app/shared/lib/angular-modal/modal/modal.component.ts
- src/app/shared/services/error/GPServiceError.ts
- src/app/shared/services/error/GlobalErrorHandler.ts
- src/app/shared/services/error/notification.service.ts
- src/styles.scss
> Add custom error class to separate generic errors

- src/app/mapmyproperty/esrimap/esrimap.component.ts
- src/app/planmylandoperation/esrimap/esrimap.component.ts
- src/app/shared/utils/SketchViewModelUitls.ts
> Add snapping on draw tools #289
